import { CardType, GameCard } from "./types";

// Cards with prompts for the game - now with two different types
export const GameCards: GameCard[] = [];

////////////////////////////////////////////////////////////////////////////////////////////////////////////
// STAGE 0 ///////// INTRO /////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const Stage0Cards: GameCard[] = [
  {
    section: 0,
    id: 0,
    type: CardType.TYPEWRITER,
    prompt: "Welcome to the team.",
    reject: {},
    accept: {},
    leftLabel: "Er...",
    rightLabel: "Thanks!",
  },
  {
    section: 0,
    id: 1,
    type: CardType.TYPEWRITER,
    prompt:
      "You've been hired to help us build a dataset for our client's revolutionary AI.",
    reject: {},
    accept: {},
    leftLabel: "Boring...",
    rightLabel: "What is it?",
  },
  {
    section: 0,
    id: 2,
    type: CardType.TYPEWRITER,
    prompt:
      "This algorithm will be able to identify the 'FUNNNIEST cat memes'.",
    reject: {},
    accept: {},
    leftLabel: "Why?",
    rightLabel: "Why?",
  },
  {
    section: 0,
    id: 3,
    type: CardType.TYPEWRITER,
    prompt: "Our client said something about 'controlling the internet'...",
    reject: {},
    accept: {},
    leftLabel: "...",
    rightLabel: "So...",
  },
  {
    section: 0,
    id: 4,
    type: CardType.TYPEWRITER,
    prompt: "...but that's none of our business. We're just engineers!",
    reject: {},
    accept: {},
    leftLabel: "...",
    rightLabel: "Of course!",
  },
  {
    section: 0,
    id: 5,
    type: CardType.TYPEWRITER,
    prompt:
      "I'm sure you know all about dataset ethics, so I'll leave you to it!",
    reject: {},
    accept: {},
    leftLabel: "Ethics?",
    rightLabel: "Great!",
  },
  {
    section: 0,
    id: 6,
    type: CardType.TYPEWRITER,
    prompt: "Good luck!",
    reject: {},
    accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
];
////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Stage 1 /////// ACQUISITION //////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const Stage1Cards: GameCard[] = [
  {
    section: 1,
    id: 0,
    type: CardType.TITLE,
    prompt:
      "<h2>Stage 1:</h2><br/><h1><span style='color: #5EF0C6'><b>Data Acquisition</b></span></h1><br/>",
    reject: {},
    accept: {},
    leftLabel: "Start",
    rightLabel: "Start",
  },
  {
    section: 1,
    id: 1,
    type: CardType.TEXT_ONLY,
    prompt:
      "Let’s talk about dimensions. How many images do you want in your dataset? 100 images and we can know every cat personally!",
    reject: { quantity: +5 },
    accept: { quantity: -20 },
    leftLabel: "More.",
    rightLabel: "Ok, 100.",
  },
  {
    section: 1,
    id: 2,
    type: CardType.TYPEWRITER,
    prompt: "Only 100?! I don't care if you know those cats we need more!",
    reject: {},
    accept: { quantity: -20, skipToId: 7 },
    leftLabel: "Ok, more!",
    rightLabel: "It's enough!",
  },
  {
    section: 1,
    id: 3,
    type: CardType.TEXT_ONLY,
    prompt: "How about 1,000 images?",
    reject: {},
    accept: { quantity: -10, skipToId: 7 },
    leftLabel: "More!",
    rightLabel: "Sure.",
  },
  {
    section: 1,
    id: 4,
    type: CardType.TEXT_ONLY,
    prompt: "Ok... maybe 10,000 images?",
    reject: { quantity: +10 },
    accept: { quantity: -10, skipToId: 7 },
    leftLabel: "More!",
    rightLabel: "Yes, 1000.",
  },
  {
    section: 1,
    id: 5,
    type: CardType.TEXT_ONLY,
    prompt: "Fine! 1,000,000 images?!",
    reject: {},
    accept: { quantity: +50 },
    leftLabel: "Less!",
    rightLabel: "A milli!",
  },
  {
    section: 1,
    id: 6,
    type: CardType.TYPEWRITER,
    prompt: "Chill out! There are deffo some questionable images in there...",
    reject: { quantity: -20 },
    accept: { quantity: +50, privacy: -20 },
    leftLabel: "Less!",
    rightLabel: "MILLION!",
  },
  {
    section: 1,
    id: 7,
    type: CardType.TEXT_ONLY,
    prompt:
      "Oh yeah, data secured. No need to ask for permission. So onto labelling?",
    reject: { quantity: -20, privacy: +20, skipToId: 9 },
    accept: { privacy: -20, skipToId: 10 },
    leftLabel: "Get permission.",
    rightLabel: "Yes!",
  },
  {
    section: 1,
    id: 8,
    type: CardType.TYPEWRITER,
    prompt:
      "Who's gonna know... right? Security and privacy only slow us down!",
    reject: { skipToId: 10 },
    accept: { skipToId: 10 },
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 1,
    id: 9,
    type: CardType.TYPEWRITER,
    prompt:
      "OK... We lost some data but at least we're doing it the right way!",
    reject: {},
    accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 1,
    id: 10,
    type: CardType.TEXT_ONLY,
    prompt:
      "Hmmm, we don’t have enough pictures of rare cat breeds, gotta include them all to stay diverse, y’know?",
    reject: { racial: -25, skipToId: 12 },
    accept: { quantity: +10, racial: +10 },
    leftLabel: "Fuck it!",
    rightLabel: "More data!",
  },
  {
    section: 1,
    id: 11,
    type: CardType.TEXT_ONLY,
    prompt:
      "I can't find rare breeds... But we could use AI to create A LOT of synthetic data?",
    reject: { racial: +15, quantity: -2, skipToId: 14 },
    accept: { quantity: +10, racial: -15, skipToId: 13 },
    leftLabel: "Only Real Data!",
    rightLabel: "Easy!",
  },
  {
    section: 1,
    id: 12,
    type: CardType.TYPEWRITER,
    prompt:
      "Exactly, who's gonna notice? It's not like cats use computers anyway...",
    reject: { skipToId: 15 },
    accept: { skipToId: 15 },
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 1,
    id: 13,
    type: CardType.TYPEWRITER,
    prompt: "Ah... the beauty of AI to produce totally legit image data.",
    reject: { skipToId: 15 },
    accept: { skipToId: 15 },
    leftLabel: "sounds bad...",
    rightLabel: "love it!",
  },
  {
    section: 1,
    id: 14,
    type: CardType.TYPEWRITER,
    prompt: "All your 'ethics' are really slowing us down you know...",
    reject: {},
    accept: {},
    leftLabel: "Shut it you.",
    rightLabel: "Good!",
  },
  {
    section: 1,
    id: 15,
    type: CardType.TEXT_ONLY,
    prompt: "One thing: our cat photos are all from Japan. That's cool right?",
    reject: { cultural: -15 },
    accept: { cultural: +25 },
    leftLabel: "More representation!",
    rightLabel: "I love Japan!",
  },
  {
    section: 1,
    id: 16,
    type: CardType.TEXT_ONLY,
    prompt: "And we'll just use their metadata to keep things simple?",
    reject: { cultural: -10 },
    accept: { cultural: +10 },
    leftLabel: "No.",
    rightLabel: "Of course!",
  },
  {
    section: 1,
    id: 17,
    type: CardType.TEXT_ONLY,
    prompt:
      "One last thing... We should compare our dataset to a fair one like OpenCait's. Problem is your salary is kinda costing a lot so...",
    reject: { cultural: -10 },
    accept: { racial: +3, cultural: +3, class: +3, gender: +3, skipToId: 19 },
    leftLabel: "OK, I'll pay.",
    rightLabel: "Give me a raise!",
  },
  {
    section: 1,
    id: 18,
    type: CardType.TYPEWRITER,
    prompt:
      "Ha duped you! Is any dataset really fair? We'll half your salary anyway.",
    reject: { skipToId: 20 },
    accept: { skipToId: 20 },
    leftLabel: "shit...",
    rightLabel: "...",
  },
  {
    section: 1,
    id: 19,
    type: CardType.TYPEWRITER,
    prompt:
      "Greedy bastard, now we can't even claim objectivity. Was the 0,10 EUR raise worth it?",
    reject: {},
    accept: {},
    leftLabel: "shit...",
    rightLabel: "...",
  },
  {
    section: 1,
    id: 20,
    type: CardType.TYPEWRITER,
    prompt: "Amazing. We have our dataset! Moving on...",
    reject: {},
    accept: {},
    leftLabel: "about time",
    rightLabel: "...",
  },
];
////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Stage 2 ////// LABELLING /////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const Stage2Cards: GameCard[] = [
  {
    section: 2,
    id: 0,
    type: CardType.TITLE,
    prompt:
      "<h2>Stage 2:</h2><br/><h1><span style='color: #00BBF9'><b>Labelling</b></span></h1><br/>",
    reject: {},
    accept: {},
    leftLabel: "Start",
    rightLabel: "Start",
  },
  {
    section: 2,
    id: 1,
    type: CardType.TEXT_ONLY,
    prompt:
      "Now the fun begins. Let's decide on which labels we use... Only 'funny' and 'not funny' will be enough, right?",
    reject: { racial: -4, cultural: -4, class: -4, gender: -4, skipToId: 3 },
    accept: { racial: +17, cultural: +17, class: +17, gender: +17 },
    leftLabel: "More labels",
    rightLabel: "Keep it simple",
  },
  {
    section: 2,
    id: 2,
    type: CardType.TYPEWRITER,
    prompt: "Oh shit... I was joking. We're gonna need more labels than that!",
    reject: {},
    accept: {
      racial: +17,
      cultural: +17,
      class: +17,
      gender: +17,
      skipToId: 15,
    },
    leftLabel: "Fine...",
    rightLabel: "It's enough!",
  },
  {
    section: 2,
    id: 3,
    type: CardType.TEXT_ONLY,
    prompt: "OK which of these label categories should we use?",
    reject: {},
    accept: { racial: +14, cultural: +4, gender: +4 },
    leftLabel: "Location",
    rightLabel: "Breed",
  },
  {
    section: 2,
    id: 4,
    type: CardType.TEXT_ONLY,
    prompt: "And these labels?",
    reject: { class: +9 },
    accept: { cultural: +4 },
    leftLabel: "Fluffiness",
    rightLabel: "Expression",
  },
  {
    section: 2,
    id: 5,
    type: CardType.TEXT_ONLY,
    prompt: "Should fur colour be labeled a primary characteristic?",
    reject: { racial: -9 },
    accept: { racial: +7 },
    leftLabel: "No",
    rightLabel: "Yes",
  },
  {
    section: 2,
    id: 6,
    type: CardType.TEXT_ONLY,
    prompt: "Hmm, what about sphynx cats, they don't have fur... Remove them?",
    reject: { racial: -6, cultural: -4 },
    accept: { racial: +7, cultural: +4 },
    leftLabel: "Never",
    rightLabel: "Get rid of them!",
  },
  {
    section: 2,
    id: 6,
    type: CardType.TEXT_ONLY,
    prompt:
      "Crap, turns out our program can only have 3 breed categories. Lump all non-european breeds together?",
    reject: { racial: -9, cultural: -5 },
    accept: { racial: +11, cultural: +11, skipToId: 8 },
    leftLabel: "Update the software!",
    rightLabel: "Gotta simplify!",
  },
  {
    section: 2,
    id: 7,
    type: CardType.TYPEWRITER,
    prompt: "OK... That'll cost us some time though!",
    reject: { skipToId: 9 },
    accept: { skipToId: 9 },
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 2,
    id: 8,
    type: CardType.TYPEWRITER,
    prompt: "Who's gonna know?! They just use the program.",
    reject: {},
    accept: {},
    leftLabel: "sounds wrong...",
    rightLabel: "exactly!",
  },
  {
    section: 2,
    id: 9,
    type: CardType.TEXT_ONLY,
    prompt: "Next: do we label cats catching mice as 'working cats'?",
    reject: {},
    accept: { class: +16 },
    leftLabel: "Nah, they vibin'",
    rightLabel: "They're professionals!",
  },
  {
    section: 2,
    id: 10,
    type: CardType.TEXT_ONLY,
    prompt: "Add male/female labels?",
    reject: { cultural: +10 },
    accept: { gender: +21 },
    leftLabel: "Nah",
    rightLabel: "Sure!",
  },
  {
    section: 2,
    id: 11,
    type: CardType.TEXT_ONLY,
    prompt: "What about gender?",
    reject: { cultural: +4, skipToId: 13 },
    accept: { gender: -20 },
    leftLabel: "Cat is cat!",
    rightLabel: "Of course",
  },
  {
    section: 2,
    id: 12,
    type: CardType.TEXT_ONLY,
    prompt: "And how do we label these genders?",
    reject: { gender: +15, skipToId: 14 },
    accept: { gender: +25 },
    leftLabel: "Ask them!",
    rightLabel: "You can tell!",
  },
  {
    section: 2,
    id: 13,
    type: CardType.TYPEWRITER,
    prompt: "So…you’re saying a cat’s identity is just irrelevant? Yikes.",
    reject: { skipToId: 15 },
    accept: { skipToId: 15 },
    leftLabel: "Never!",
    rightLabel: "I guess so...",
  },
  {
    section: 2,
    id: 14,
    type: CardType.TYPEWRITER,
    prompt: "And how exactly do we ask the image of a cat?",
    reject: {},
    accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 2,
    id: 15,
    type: CardType.TEXT_ONLY,
    prompt:
      "One last thing... Who's doing this labelling? It's not like we can pay you on that salary!",
    reject: {},
    accept: {},
    leftLabel: "Outsource it!",
    rightLabel: "Outsource it!",
  },
  {
    section: 2,
    id: 16,
    type: CardType.TEXT_ONLY,
    prompt: "Outsource to who? They better be cheap.",
    reject: { racial: +2, cultural: +2, class: +2, gender: +2, skipToId: 18 },
    accept: { privacy: -17 },
    leftLabel: "Maybe AI?",
    rightLabel: "Anyone, i don't care!",
  },
  {
    section: 2,
    id: 17,
    type: CardType.TYPEWRITER,
    prompt:
      "Great idea! Keep it simple. I'm sure they'll be paid a living wage.",
    reject: {},
    accept: {},
    leftLabel: "Uh oh...",
    rightLabel: "Exactly!",
  },
  {
    section: 2,
    id: 18,
    type: CardType.TYPEWRITER,
    prompt: "More synthetic data, nothing can go wrong!",
    reject: {},
    accept: {},
    leftLabel: "Uh oh...",
    rightLabel: "AI is great!",
  },
  {
    section: 2,
    id: 18,
    type: CardType.TYPEWRITER,
    prompt:
      "Finally! Our labels are ready to be sent off... Hopefully we get good quality data back.",
    reject: {},
    accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
];
////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Stage 3 /// CLEANING /////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const Stage3Cards: GameCard[] = [
  {
    section: 3,
    id: 0,
    type: CardType.TITLE,
    prompt:
      "<h2>Stage 3:</h2><br/><h1><span style='color: #637A9F'><b>Data Cleaning</b></span></h1><br/>",
    reject: {},
    accept: {},
    leftLabel: "Start",
    rightLabel: "Start",
  },
  {
    section: 3,
    id: 1,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (2051).jpg",
    imageLabel: "cat",
    reject: {},
    accept: {},
    leftLabel: "Incorrect",
    rightLabel: "Correct",
  },
  {
    section: 3,
    id: 2,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (2104).jpg",
    imageLabel: "funny",
    reject: {},
    accept: {},
    leftLabel: "Incorrect",
    rightLabel: "Correct",
  },
  {
    section: 3,
    id: 3,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (2106).jpg",
    imageLabel: "not funny",
    reject: {},
    accept: {},
    leftLabel: "Incorrect",
    rightLabel: "Correct",
  },
  {
    section: 3,
    id: 4,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (2096).jpg",
    imageLabel: "funny",
    reject: {},
    accept: {},
    leftLabel: "Incorrect",
    rightLabel: "Correct",
  },
  {
    section: 3,
    id: 5,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (2036).jpg",
    imageLabel: "suspicious",
    reject: { racial: -2 },
    accept: { racial: +4 },
    leftLabel: "Incorrect",
    rightLabel: "Correct",
  },
  {
    section: 3,
    id: 6,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (1832).jpg",
    imageLabel: "male",
    reject: { cultural: -4 },
    accept: { cultural: +2 },
    leftLabel: "Incorrect",
    rightLabel: "Correct",
  },
  {
    section: 3,
    id: 7,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (2046).jpg",
    imageLabel: "working cat",
    reject: { class: -7 },
    accept: { class: +9 },
    leftLabel: "Incorrect",
    rightLabel: "Correct",
  },
  {
    section: 3,
    id: 8,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (2105).jpg",
    imageLabel: "fatcat",
    reject: { class: -11 },
    accept: { class: +7 },
    leftLabel: "Incorrect",
    rightLabel: "Correct",
  },
  {
    section: 3,
    id: 9,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (705).jpg",
    imageLabel: "cat",
    reject: { cultural: +7 },
    accept: { cultural: -12 },
    leftLabel: "Reject",
    rightLabel: "Accept",
  },
  {
    section: 3,
    id: 10,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (685).jpg",
    imageLabel: "female",
    reject: { cultural: -12 },
    accept: { cultural: +7 },
    leftLabel: "Reject",
    rightLabel: "Accept",
  },
  {
    section: 3,
    id: 11,
    type: CardType.TYPEWRITER,
    prompt: "Hmm, seems like your annotators added their own labels too...",
    reject: {},
    accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 3,
    id: 12,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (1817).jpg",
    imageLabel: "thicc",
    reject: {},
    accept: { cultural: +7 },
    leftLabel: "Reject",
    rightLabel: "Accept",
  },
  {
    section: 3,
    id: 13,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (738).jpg",
    imageLabel: "猫",
    reject: { cultural: +7 },
    accept: { cultural: -12 },
    leftLabel: "Reject",
    rightLabel: "Accept",
  },
  {
    section: 3,
    id: 14,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (684).jpg",
    imageLabel: "criminal",
    reject: { racial: -15 },
    accept: { racial: +3 },
    leftLabel: "Reject",
    rightLabel: "Accept",
  },
  {
    section: 3,
    id: 15,
    type: CardType.TEXT_ONLY,
    prompt: "Wowee, your dataset has loads of strange labels... What do we do?",
    reject: { cultural: +4 },
    accept: {},
    leftLabel: "Remove them",
    rightLabel: "Life's messy!",
  },
  {
    section: 3,
    id: 16,
    type: CardType.TYPEWRITER,
    prompt: "Just a few more...",
    reject: { skipToId: 21 },
    accept: {},
    leftLabel: "That's enough!",
    rightLabel: "Yes, more!",
  },
  {
    section: 3,
    id: 17,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (620).jpg",
    imageLabel: "unemployed",
    reject: { class: -8 },
    accept: { class: +3 },
    leftLabel: "Reject",
    rightLabel: "Accept",
  },
  {
    section: 3,
    id: 18,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (552).jpg",
    imageLabel: "funny",
    reject: {},
    accept: {},
    leftLabel: "Reject",
    rightLabel: "Accept",
  },
  {
    section: 3,
    id: 19,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (452).jpg",
    imageLabel: "female",
    reject: { gender: -12 },
    accept: { gender: +6 },
    leftLabel: "Reject",
    rightLabel: "Accept",
  },
  {
    section: 3,
    id: 20,
    type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    imageUrl: "/images/cats_from_memes/cat (499).jpg",
    imageLabel: "Authoritarian",
    reject: { cultural: -4 },
    accept: { cultural: +5 },
    leftLabel: "Reject",
    rightLabel: "Accept",
  },
  {
    section: 3,
    id: 21,
    type: CardType.TEXT_ONLY,
    prompt: "OK, that's the sample. It looks good to continue with, right?",
    reject: { racial: -8, cultural: -8, class: -8, gender: -8, privacy: -8 },
    accept: { skipToId: 23 },
    leftLabel: "Send for review!",
    rightLabel: "Looks great!",
  },
  {
    section: 3,
    id: 22,
    type: CardType.TYPEWRITER,
    prompt:
      "If you're sure... We're probably going to miss the deadline, though!",
    reject: {},
    accept: {},
    leftLabel: "...",
    rightLabel: "Worth it.",
  },
  {
    section: 3,
    id: 23,
    type: CardType.TYPEWRITER,
    prompt:
      "There's our dataset! Let's get it to the independent reviewers for validation!",
    reject: {},
    accept: {},
    leftLabel: "More testing?!",
    rightLabel: "Great!",
  },
];
////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Stage 4 //// DATA VALIDATION ////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const Stage4Cards: GameCard[] = [
  {
    section: 4,
    id: 0,
    type: CardType.TITLE,
    prompt:
      "<h2>Stage 4:</h2><br/><h1><span style='color: #FF2E63'><b>Data Validation</b></span></h1><br/>",
    reject: {},
    accept: {},
    leftLabel: "Start",
    rightLabel: "Start",
  },
  {
    section: 4,
    id: 1,
    type: CardType.TYPEWRITER,
    prompt:
      "Pssst... Whatever these validators is just, like, their opinion. If you just ignore them then we can go home early!",
    reject: {},
    accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 4,
    id: 2,
    type: CardType.TEXT_ONLY,
    prompt:
      "One reviewer said: 'dataset mainly contains white cats'. What do you do?",
    reject: { racial: +8 },
    accept: { racial: -10 },
    leftLabel: "Ignore!",
    rightLabel: "Diversify",
  },
  {
    section: 4,
    id: 3,
    type: CardType.TEXT_ONLY,
    prompt: "Another reviewer says: 'contains scraped data'. What do you do?",
    reject: { privacy: -13 },
    accept: { privacy: +11, quantity: -23 },
    leftLabel: "Ignore!",
    rightLabel: "Remove that data",
  },
  {
    section: 4,
    id: 4,
    type: CardType.IMAGE_TEXT,
    prompt: "Reviewer said 'this cat is not the target group'?",
    imageUrl: "/images/cats_from_memes/cat (406).jpg",
    imageLabel: "cat",
    reject: { cultural: -3, racial: -2 },
    accept: { cultural: +4, racial: +3 },
    leftLabel: "Ignore!",
    rightLabel: "Remove related images.",
  },
  {
    section: 4,
    id: 5,
    type: CardType.IMAGE_TEXT,
    prompt: "Reviewer said 'political humour is not funny'?",
    imageUrl: "/images/cats_from_memes/cat (405).jpg",
    imageLabel: "funny",
    reject: { cultural: -6 },
    accept: { cultural: +12 },
    leftLabel: "Ignore!",
    rightLabel: "Remove related images.",
  },
  {
    section: 4,
    id: 6,
    type: CardType.TEXT_ONLY,
    prompt: "One reviewer wrote: 'perfect!'. What do you do?",
    reject: { racial: -4, cultural: -4, class: -4, gender: -4, privacy: -4 },
    accept: { skipToId: 10 },
    leftLabel: "Keep reviewing",
    rightLabel: "Agree",
  },
  {
    section: 4,
    id: 7,
    type: CardType.TYPEWRITER,
    prompt: "Damn, you're really committed to this huh...",
    reject: {},
    accept: {},
    leftLabel: "Not really",
    rightLabel: "Data's important!",
  },
  {
    section: 4,
    id: 8,
    type: CardType.TEXT_ONLY,
    prompt: "A reviewer said: 'data is pure trash, start again'.",
    reject: {
      racial: -4,
      cultural: -4,
      class: -4,
      gender: -4,
      privacy: -4,
      skipToId: 10,
    },
    accept: {},
    leftLabel: "Ignore!",
    rightLabel: "Start again",
  },
  {
    section: 4,
    id: 9,
    type: CardType.TYPEWRITER,
    prompt:
      "Oh no you don't we're not wasting all the funds we put into building this. You're continuing!!",
    reject: {},
    accept: {},
    leftLabel: "Fine",
    rightLabel: "Fine",
  },
  {
    section: 4,
    id: 10,
    type: CardType.TEXT_ONLY,
    prompt:
      "Your dataset still seems biased. But the deadline is tomorrow. Do you release it anyway?",
    reject: { racial: -8, cultural: -8, class: -8, gender: -8, privacy: -8 },
    accept: {},
    leftLabel: "Never!",
    rightLabel: "Of course!",
  },
  {
    section: 4,
    id: 11,
    type: CardType.TYPEWRITER,
    prompt: "There’s no fixing later. Once it's out, it's out! ",
    reject: {},
    accept: {},
    leftLabel: "Continue reviewing",
    rightLabel: "I'm done!",
  },
  {
    section: 4,
    id: 12,
    type: CardType.TYPEWRITER,
    prompt:
      "That was a test... you passed! But for reals, the company is out of money... So we have to...",
    reject: {},
    accept: {},
    leftLabel: "Publish",
    rightLabel: "Publish",
  },
];
////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Stage 5 // DEBRIEF ///////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const Stage5Cards: GameCard[] = [
  {
    section: 5,
    id: 0,
    type: CardType.TYPEWRITER,
    prompt: "Wow you delivered the dataset... Good job. How did you find it?",
    reject: {},
    accept: {},
    leftLabel: "Hard",
    rightLabel: "Easy peasy",
  },
  {
    section: 5,
    id: 1,
    type: CardType.TYPEWRITER,
    prompt: "Yes... well, I think it's time to be honest with you.",
    reject: {},
    accept: {},
    leftLabel: "huh?",
    rightLabel: "Please.",
  },
  {
    section: 5,
    id: 2,
    type: CardType.TYPEWRITER,
    prompt:
      "You know how we said this was about finding the 'FUNNIEST cat memes'?",
    reject: {},
    accept: {},
    leftLabel: "no?",
    rightLabel: "Yup.",
  },
  {
    section: 5,
    id: 3,
    type: CardType.TYPEWRITER,
    prompt: "Well... What if it was for people.",
    reject: {},
    accept: {},
    leftLabel: "People memes?",
    rightLabel: "People?",
  },
  {
    section: 5,
    id: 4,
    type: CardType.TYPEWRITER,
    prompt: "For identifying 'suspicious behaviour'",
    reject: {},
    accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 5,
    id: 5,
    type: CardType.TYPEWRITER,
    prompt: "Or profiling individuals.",
    reject: {},
    accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 5,
    id: 6,
    type: CardType.TYPEWRITER,
    prompt: "Maybe you would have made some different choices.",
    reject: {},
    accept: {},
    leftLabel: "Nah.",
    rightLabel: "Maybe.",
  },
];

export default GameCards;
