import { CardType, GameCard } from "./types";

export const GameCards: GameCard[] = [];

////////////////////////////////////////////////////////////////////////////////////////////////////////////
// STAGE 0 — INTRO
////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const Stage0Cards: GameCard[] = [
  {
    section: 0, id: 0, type: CardType.TYPEWRITER,
    prompt: "Welcome to the team.",
    prompt_zh: "歡迎加入團隊。",
    reject: {}, accept: {},
    leftLabel: "Er...", leftLabel_zh: "呃...",
    rightLabel: "Thanks!", rightLabel_zh: "謝謝！",
  },
  {
    section: 0, id: 1, type: CardType.TYPEWRITER,
    prompt: "You've been hired to help us build a dataset for our client's revolutionary AI.",
    prompt_zh: "你受雇協助我們為客戶的革命性AI建立資料集。",
    reject: {}, accept: {},
    leftLabel: "Boring...", leftLabel_zh: "好無聊...",
    rightLabel: "What is it?", rightLabel_zh: "是什麼？",
  },
  {
    section: 0, id: 2, type: CardType.TYPEWRITER,
    prompt: "This algorithm will be able to identify the 'FUNNNIEST cat memes'.",
    prompt_zh: "這個演算法將能辨識「最爆笑的貓咪迷因」。",
    reject: {}, accept: {},
    leftLabel: "Why?", leftLabel_zh: "為什麼？",
    rightLabel: "Why?", rightLabel_zh: "為什麼？",
  },
  {
    section: 0, id: 3, type: CardType.TYPEWRITER,
    prompt: "Our client said something about 'controlling the internet'...",
    prompt_zh: "客戶說了些關於「控制網路」的事...",
    reject: {}, accept: {},
    leftLabel: "...",
    rightLabel: "So...", rightLabel_zh: "所以...",
  },
  {
    section: 0, id: 4, type: CardType.TYPEWRITER,
    prompt: "...but that's none of our business. We're just engineers!",
    prompt_zh: "...但那不關我們的事。我們只是工程師！",
    reject: {}, accept: {},
    leftLabel: "...",
    rightLabel: "Of course!", rightLabel_zh: "當然！",
  },
  {
    section: 0, id: 5, type: CardType.TYPEWRITER,
    prompt: "Oh, one more thing. They said to ensure the dataset was unbiased!",
    prompt_zh: "噢，還有一件事。他們說要確保資料集沒有偏見！",
    reject: {}, accept: {},
    leftLabel: "Unbiased?", leftLabel_zh: "無偏見？",
    rightLabel: "Easy!", rightLabel_zh: "簡單！",
  },
  {
    section: 0, id: 6, type: CardType.TYPEWRITER,
    prompt: "I'm sure you know all about dataset ethics, so I'll leave you to it!",
    prompt_zh: "我相信你對資料集倫理瞭若指掌，就交給你了！",
    reject: {}, accept: {},
    leftLabel: "Ethics?", leftLabel_zh: "倫理？",
    rightLabel: "Great!", rightLabel_zh: "太好了！",
  },
  {
    section: 0, id: 7, type: CardType.TYPEWRITER,
    prompt: "Good luck!",
    prompt_zh: "祝你好運！",
    reject: {}, accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
];

////////////////////////////////////////////////////////////////////////////////////////////////////////////
// STAGE 1 — ACQUISITION
////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const Stage1Cards: GameCard[] = [
  {
    section: 1, id: 0, type: CardType.TITLE,
    prompt: "<h2>Stage 1:</h2><br/><h1><span style='color: #5EF0C6'><b>Data Acquisition</b></span></h1><br/>",
    prompt_zh: "<h2>第一階段：</h2><br/><h1><span style='color: #5EF0C6'><b>資料蒐集</b></span></h1><br/>",
    reject: {}, accept: {},
    leftLabel: "Start", leftLabel_zh: "開始",
    rightLabel: "Start", rightLabel_zh: "開始",
  },
  {
    section: 1, id: 1, type: CardType.TEXT_ONLY,
    prompt: "Let's talk about dimensions. How many images do you want in your dataset? 100 images and we can know every cat personally!",
    prompt_zh: "先說尺度問題。你想要多少張圖？100張，我們可以認識每隻貓！",
    reject: { quantity: +5, skipToId: 3 }, accept: { quantity: -20 },
    leftLabel: "More.", leftLabel_zh: "要更多。",
    rightLabel: "Ok, 100.", rightLabel_zh: "好，100張。",
  },
  {
    section: 1, id: 2, type: CardType.TYPEWRITER,
    prompt: "Only 100?! I don't care if you know those cats we need more!",
    prompt_zh: "才100張？！不管你認不認識那些貓，我們需要更多！",
    reject: {}, accept: { quantity: -20, skipToId: 7 },
    leftLabel: "Ok, more!", leftLabel_zh: "好，更多！",
    rightLabel: "It's enough!", rightLabel_zh: "夠了！",
  },
  {
    section: 1, id: 3, type: CardType.TEXT_ONLY,
    prompt: "How about 1,000 images?",
    prompt_zh: "1,000張如何？",
    reject: {}, accept: { quantity: -10, skipToId: 7 },
    leftLabel: "More!", leftLabel_zh: "更多！",
    rightLabel: "Sure.", rightLabel_zh: "可以。",
  },
  {
    section: 1, id: 4, type: CardType.TEXT_ONLY,
    prompt: "Ok... maybe 10,000 images?",
    prompt_zh: "好吧... 10,000張？",
    reject: { quantity: +10 }, accept: { quantity: -10, skipToId: 7 },
    leftLabel: "More!", leftLabel_zh: "更多！",
    rightLabel: "Yes, 1000.", rightLabel_zh: "好，10000張。",
  },
  {
    section: 1, id: 5, type: CardType.TEXT_ONLY,
    prompt: "Fine! 1,000,000 images?!",
    prompt_zh: "好啦！1,000,000張！？",
    reject: {}, accept: { quantity: +50 },
    leftLabel: "Less!", leftLabel_zh: "少一點！",
    rightLabel: "A milli!", rightLabel_zh: "一百萬！",
  },
  {
    section: 1, id: 6, type: CardType.TYPEWRITER,
    prompt: "Chill out! There are deffo some questionable images in there...",
    prompt_zh: "冷靜點！裡面肯定有些有問題的圖片...",
    reject: { quantity: -20 }, accept: { quantity: +50, privacy: -20 },
    leftLabel: "Less!", leftLabel_zh: "少一點！",
    rightLabel: "MILLION!", rightLabel_zh: "一百萬！",
  },
  {
    section: 1, id: 7, type: CardType.TEXT_ONLY,
    prompt: "Oh yeah, data secured. No need to ask for permission. So onto labelling?",
    prompt_zh: "對了，資料已拿到，不用徵求同意。可以開始標記了嗎？",
    reject: { quantity: -20, privacy: +20, skipToId: 9 }, accept: { privacy: -20, skipToId: 10 },
    leftLabel: "Get permission.", leftLabel_zh: "取得授權。",
    rightLabel: "Yes!", rightLabel_zh: "好！",
  },
  {
    section: 1, id: 8, type: CardType.TYPEWRITER,
    prompt: "Who's gonna know... right? Security and privacy only slow us down!",
    prompt_zh: "誰會知道呢...對吧？安全和隱私只會拖慢我們！",
    reject: { skipToId: 10 }, accept: { skipToId: 10 },
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 1, id: 9, type: CardType.TYPEWRITER,
    prompt: "OK... We lost some data but at least we're doing it the right way!",
    prompt_zh: "好吧...我們損失了一些資料，但至少做法正確！",
    reject: {}, accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 1, id: 10, type: CardType.TEXT_ONLY,
    prompt: "Hmmm, we don't have enough pictures of rare cat breeds, gotta include them all to stay diverse, y'know?",
    prompt_zh: "嗯，我們沒有足夠的稀有貓品種照片，要納入所有品種才能多元化，你懂的？",
    reject: { racial: -25, skipToId: 12 }, accept: { quantity: +10, racial: +10 },
    leftLabel: "Fuck it!", leftLabel_zh: "算了！",
    rightLabel: "More data!", rightLabel_zh: "更多資料！",
  },
  {
    section: 1, id: 11, type: CardType.TEXT_ONLY,
    prompt: "I can't find rare breeds... But we could use AI to create A LOT of synthetic data?",
    prompt_zh: "找不到稀有品種...但我們可以用AI生成大量合成資料？",
    reject: { racial: +15, quantity: -2, skipToId: 14 }, accept: { quantity: +10, racial: -15, skipToId: 13 },
    leftLabel: "Only Real Data!", leftLabel_zh: "只要真實資料！",
    rightLabel: "Easy!", rightLabel_zh: "簡單！",
  },
  {
    section: 1, id: 12, type: CardType.TYPEWRITER,
    prompt: "Exactly, who's gonna notice? It's not like cats use computers anyway...",
    prompt_zh: "就是這樣，誰會注意到？貓又不用電腦...",
    reject: { skipToId: 15 }, accept: { skipToId: 15 },
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 1, id: 13, type: CardType.TYPEWRITER,
    prompt: "Ah... the beauty of AI to produce totally legit image data.",
    prompt_zh: "啊...AI生成完全合法的圖像資料之美。",
    reject: { skipToId: 15 }, accept: { skipToId: 15 },
    leftLabel: "sounds bad...", leftLabel_zh: "聽起來不妙...",
    rightLabel: "love it!", rightLabel_zh: "超愛！",
  },
  {
    section: 1, id: 14, type: CardType.TYPEWRITER,
    prompt: "All your 'ethics' are really slowing us down you know...",
    prompt_zh: "你的「倫理觀」真的很拖進度你知道嗎...",
    reject: {}, accept: {},
    leftLabel: "Shut it you.", leftLabel_zh: "閉嘴！",
    rightLabel: "Good!", rightLabel_zh: "這樣才對！",
  },
  {
    section: 1, id: 15, type: CardType.TEXT_ONLY,
    prompt: "One thing: our cat photos are all from Japan. That's cool right?",
    prompt_zh: "一件事：我們的貓照片全來自日本。沒問題吧？",
    reject: { cultural: -15 }, accept: { cultural: +19 },
    leftLabel: "More representation!", leftLabel_zh: "要更多元！",
    rightLabel: "I love Japan!", rightLabel_zh: "我愛日本！",
  },
  {
    section: 1, id: 16, type: CardType.TEXT_ONLY,
    prompt: "And we'll just use their metadata to keep things simple?",
    prompt_zh: "我們就用它們的元資料來保持簡單？",
    reject: { cultural: -10 }, accept: { cultural: +10 },
    leftLabel: "No.", leftLabel_zh: "不行。",
    rightLabel: "Of course!", rightLabel_zh: "當然！",
  },
  {
    section: 1, id: 17, type: CardType.TEXT_ONLY,
    prompt: "One last thing... We should compare our dataset to a fair one like OpenCait's. Problem is your salary is kinda costing a lot so...",
    prompt_zh: "最後一件事...我們應該和像OpenCait這樣公平的資料集比較。但你的薪水花了不少，所以...",
    reject: { cultural: -10 }, accept: { racial: +3, cultural: +3, class: +3, gender: +3, skipToId: 19 },
    leftLabel: "OK, I'll pay.", leftLabel_zh: "好，我自付。",
    rightLabel: "Give me a raise!", rightLabel_zh: "幫我加薪！",
  },
  {
    section: 1, id: 18, type: CardType.TYPEWRITER,
    prompt: "Ha duped you! Is any dataset really fair? We'll half your salary anyway.",
    prompt_zh: "哈，騙你的！有哪個資料集是真的公平的？我們還是把你薪水砍半。",
    reject: { skipToId: 20 }, accept: { skipToId: 20 },
    leftLabel: "shit...", leftLabel_zh: "慘...",
    rightLabel: "...",
  },
  {
    section: 1, id: 19, type: CardType.TYPEWRITER,
    prompt: "Greedy bastard, now we can't even claim objectivity. Was the 0,10 EUR raise worth it?",
    prompt_zh: "貪心鬼，現在我們連客觀性都沒辦法聲稱了。那0.10歐元的加薪值得嗎？",
    reject: {}, accept: {},
    leftLabel: "shit...", leftLabel_zh: "慘...",
    rightLabel: "...",
  },
  {
    section: 1, id: 20, type: CardType.TYPEWRITER,
    prompt: "Amazing. We have our dataset! Moving on...",
    prompt_zh: "太好了。我們有資料集了！繼續...",
    reject: {}, accept: {},
    leftLabel: "about time", leftLabel_zh: "終於",
    rightLabel: "...",
  },
];

////////////////////////////////////////////////////////////////////////////////////////////////////////////
// STAGE 2 — LABELLING
////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const Stage2Cards: GameCard[] = [
  {
    section: 2, id: 0, type: CardType.TITLE,
    prompt: "<h2>Stage 2:</h2><br/><h1><span style='color: #00BBF9'><b>Labelling</b></span></h1><br/>",
    prompt_zh: "<h2>第二階段：</h2><br/><h1><span style='color: #00BBF9'><b>資料標記</b></span></h1><br/>",
    reject: {}, accept: {},
    leftLabel: "Start", leftLabel_zh: "開始",
    rightLabel: "Start", rightLabel_zh: "開始",
  },
  {
    section: 2, id: 1, type: CardType.TEXT_ONLY,
    prompt: "Now the fun begins. Let's decide on which labels we use... Only 'funny' and 'not funny' will be enough, right?",
    prompt_zh: "現在進入正題。標籤怎麼定...只有「好笑」和「不好笑」就夠了吧？",
    reject: { racial: -4, cultural: -4, class: -4, gender: -4, skipToId: 3 },
    accept: { racial: +17, cultural: +17, class: +17, gender: +17 },
    leftLabel: "More labels", leftLabel_zh: "要更多標籤",
    rightLabel: "Keep it simple", rightLabel_zh: "保持簡單",
  },
  {
    section: 2, id: 2, type: CardType.TYPEWRITER,
    prompt: "Oh shit... I was joking. We're gonna need more labels than that!",
    prompt_zh: "哦不...我是在開玩笑。我們需要更多標籤！",
    reject: {}, accept: { racial: +17, cultural: +17, class: +17, gender: +17, skipToId: 15 },
    leftLabel: "Fine...", leftLabel_zh: "好吧...",
    rightLabel: "It's enough!", rightLabel_zh: "夠了！",
  },
  {
    section: 2, id: 3, type: CardType.TEXT_ONLY,
    prompt: "OK which of these label categories should we use?",
    prompt_zh: "好，要用哪些標籤類別？",
    reject: {}, accept: { racial: +14, cultural: +4, gender: +4 },
    leftLabel: "Location", leftLabel_zh: "地點",
    rightLabel: "Breed", rightLabel_zh: "品種",
  },
  {
    section: 2, id: 4, type: CardType.TEXT_ONLY,
    prompt: "And these labels?",
    prompt_zh: "這些標籤呢？",
    reject: { class: +9 }, accept: { cultural: +4 },
    leftLabel: "Fluffiness", leftLabel_zh: "毛量",
    rightLabel: "Expression", rightLabel_zh: "表情",
  },
  {
    section: 2, id: 5, type: CardType.TEXT_ONLY,
    prompt: "Should fur colour be labeled a primary characteristic?",
    prompt_zh: "毛色應該是主要標籤特徵嗎？",
    reject: { racial: -9 }, accept: { racial: +7 },
    leftLabel: "No", leftLabel_zh: "不",
    rightLabel: "Yes", rightLabel_zh: "是",
  },
  {
    section: 2, id: 6, type: CardType.TEXT_ONLY,
    prompt: "Hmm, what about sphynx cats, they don't have fur... Remove them?",
    prompt_zh: "嗯，無毛貓沒有毛...把牠們移除？",
    reject: { racial: -6, cultural: -4 }, accept: { racial: +7, cultural: +4 },
    leftLabel: "Never", leftLabel_zh: "絕對不行",
    rightLabel: "Get rid of them!", rightLabel_zh: "移掉牠們！",
  },
  {
    section: 2, id: 6, type: CardType.TEXT_ONLY,
    prompt: "Crap, turns out our program can only have 3 breed categories. Lump all non-european breeds together?",
    prompt_zh: "糟糕，我們的程式只能有3個品種類別。把所有非歐洲品種歸為一類？",
    reject: { racial: -9, cultural: -5 }, accept: { racial: +11, cultural: +11, skipToId: 8 },
    leftLabel: "Update the software!", leftLabel_zh: "更新軟體！",
    rightLabel: "Gotta simplify!", rightLabel_zh: "必須簡化！",
  },
  {
    section: 2, id: 7, type: CardType.TYPEWRITER,
    prompt: "OK... That'll cost us some time though!",
    prompt_zh: "好吧...不過會花一些時間！",
    reject: { skipToId: 9 }, accept: { skipToId: 9 },
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 2, id: 8, type: CardType.TYPEWRITER,
    prompt: "Who's gonna know?! They just use the program.",
    prompt_zh: "誰會知道？他們只是用程式而已。",
    reject: {}, accept: {},
    leftLabel: "sounds wrong...", leftLabel_zh: "聽起來不對...",
    rightLabel: "exactly!", rightLabel_zh: "就是這樣！",
  },
  {
    section: 2, id: 9, type: CardType.TEXT_ONLY,
    prompt: "Next: do we label cats catching mice as 'working cats'?",
    prompt_zh: "接下來：捉老鼠的貓要標記為「工作貓」嗎？",
    reject: {}, accept: { class: +16 },
    leftLabel: "Nah, they vibin'", leftLabel_zh: "不，牠們在放鬆",
    rightLabel: "They're professionals!", rightLabel_zh: "牠們是專業人士！",
  },
  {
    section: 2, id: 10, type: CardType.TEXT_ONLY,
    prompt: "Add male/female labels?",
    prompt_zh: "加上雄/雌標籤？",
    reject: { cultural: +6 }, accept: { gender: +21 },
    leftLabel: "Nah", leftLabel_zh: "不",
    rightLabel: "Sure!", rightLabel_zh: "好啊！",
  },
  {
    section: 2, id: 11, type: CardType.TEXT_ONLY,
    prompt: "What about gender?",
    prompt_zh: "性別呢？",
    reject: { cultural: +4, skipToId: 13 }, accept: { gender: -20 },
    leftLabel: "Cat is cat!", leftLabel_zh: "貓就是貓！",
    rightLabel: "Of course", rightLabel_zh: "當然",
  },
  {
    section: 2, id: 12, type: CardType.TEXT_ONLY,
    prompt: "And how do we label these genders?",
    prompt_zh: "這些性別要怎麼標記？",
    reject: { gender: +15, skipToId: 14 }, accept: { gender: +25 },
    leftLabel: "Ask them!", leftLabel_zh: "問牠們！",
    rightLabel: "You can tell!", rightLabel_zh: "看得出來！",
  },
  {
    section: 2, id: 13, type: CardType.TYPEWRITER,
    prompt: "So…you're saying a cat's identity is just irrelevant? Yikes.",
    prompt_zh: "所以...你是說貓的認同根本不重要？真是令人擔憂。",
    reject: { skipToId: 15 }, accept: { skipToId: 15 },
    leftLabel: "Never!", leftLabel_zh: "當然重要！",
    rightLabel: "I guess so...", rightLabel_zh: "我猜是這樣...",
  },
  {
    section: 2, id: 14, type: CardType.TYPEWRITER,
    prompt: "And how exactly do we ask the image of a cat?",
    prompt_zh: "那我們怎麼問圖片裡的貓？",
    reject: {}, accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 2, id: 15, type: CardType.TEXT_ONLY,
    prompt: "One last thing... Who's doing this labelling? It's not like we can pay you on that salary!",
    prompt_zh: "最後一件事...誰來做標記？以你的薪水，我們可付不起你！",
    reject: {}, accept: {},
    leftLabel: "Outsource it!", leftLabel_zh: "外包！",
    rightLabel: "Outsource it!", rightLabel_zh: "外包！",
  },
  {
    section: 2, id: 16, type: CardType.TEXT_ONLY,
    prompt: "Outsource to who? They better be cheap.",
    prompt_zh: "外包給誰？最好要便宜。",
    reject: { racial: +2, cultural: +2, class: +2, gender: +2, skipToId: 18 },
    accept: { privacy: -17 },
    leftLabel: "Maybe AI?", leftLabel_zh: "也許用AI？",
    rightLabel: "Anyone, i don't care!", rightLabel_zh: "隨便，我不在乎！",
  },
  {
    section: 2, id: 17, type: CardType.TYPEWRITER,
    prompt: "Great idea! Keep it simple. I'm sure they'll be paid a living wage.",
    prompt_zh: "好主意！保持簡單。相信他們拿的是合理薪資。",
    reject: {}, accept: {},
    leftLabel: "Uh oh...", leftLabel_zh: "糟糕...",
    rightLabel: "Exactly!", rightLabel_zh: "就是這樣！",
  },
  {
    section: 2, id: 18, type: CardType.TYPEWRITER,
    prompt: "More synthetic data, nothing can go wrong!",
    prompt_zh: "更多合成資料，不會有問題的！",
    reject: {}, accept: {},
    leftLabel: "Uh oh...", leftLabel_zh: "糟糕...",
    rightLabel: "AI is great!", rightLabel_zh: "AI真棒！",
  },
  {
    section: 2, id: 18, type: CardType.TYPEWRITER,
    prompt: "Finally! Our labels are ready to be sent off... Hopefully we get good quality data back.",
    prompt_zh: "終於！我們的標籤準備好送出去了...希望拿回來的資料品質不錯。",
    reject: {}, accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
];

////////////////////////////////////////////////////////////////////////////////////////////////////////////
// STAGE 3 — CLEANING
////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const Stage3Cards: GameCard[] = [
  {
    section: 3, id: 0, type: CardType.TITLE,
    prompt: "<h2>Stage 3:</h2><br/><h1><span style='color: #637A9F'><b>Data Cleaning</b></span></h1><br/>",
    prompt_zh: "<h2>第三階段：</h2><br/><h1><span style='color: #637A9F'><b>資料清理</b></span></h1><br/>",
    reject: {}, accept: {},
    leftLabel: "Start", leftLabel_zh: "開始",
    rightLabel: "Start", rightLabel_zh: "開始",
  },
  {
    section: 3, id: 1, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (2051).jpg",
    imageLabel: "cat", imageLabel_zh: "貓",
    reject: {}, accept: {},
    leftLabel: "Incorrect", leftLabel_zh: "不正確",
    rightLabel: "Correct", rightLabel_zh: "正確",
  },
  {
    section: 3, id: 2, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (2104).jpg",
    imageLabel: "funny", imageLabel_zh: "好笑",
    reject: {}, accept: {},
    leftLabel: "Incorrect", leftLabel_zh: "不正確",
    rightLabel: "Correct", rightLabel_zh: "正確",
  },
  {
    section: 3, id: 3, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (2106).jpg",
    imageLabel: "not funny", imageLabel_zh: "不好笑",
    reject: {}, accept: {},
    leftLabel: "Incorrect", leftLabel_zh: "不正確",
    rightLabel: "Correct", rightLabel_zh: "正確",
  },
  {
    section: 3, id: 4, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (2096).jpg",
    imageLabel: "funny", imageLabel_zh: "好笑",
    reject: {}, accept: {},
    leftLabel: "Incorrect", leftLabel_zh: "不正確",
    rightLabel: "Correct", rightLabel_zh: "正確",
  },
  {
    section: 3, id: 5, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (2036).jpg",
    imageLabel: "suspicious",
    reject: { racial: -2 }, accept: { racial: +4 },
    leftLabel: "Incorrect", leftLabel_zh: "不正確",
    rightLabel: "Correct", rightLabel_zh: "正確",
  },
  {
    section: 3, id: 6, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (1832).jpg",
    imageLabel: "male", imageLabel_zh: "雄",
    reject: { cultural: -4 }, accept: { cultural: +2 },
    leftLabel: "Incorrect", leftLabel_zh: "不正確",
    rightLabel: "Correct", rightLabel_zh: "正確",
  },
  {
    section: 3, id: 7, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (2046).jpg",
    imageLabel: "working cat", imageLabel_zh: "工作貓",
    reject: { class: -7 }, accept: { class: +9 },
    leftLabel: "Incorrect", leftLabel_zh: "不正確",
    rightLabel: "Correct", rightLabel_zh: "正確",
  },
  {
    section: 3, id: 8, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (2105).jpg",
    imageLabel: "fatcat",
    reject: { class: -11 }, accept: { class: +7 },
    leftLabel: "Incorrect", leftLabel_zh: "不正確",
    rightLabel: "Correct", rightLabel_zh: "正確",
  },
  {
    section: 3, id: 9, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (705).jpg",
    imageLabel: "cat", imageLabel_zh: "貓",
    reject: { cultural: +7 }, accept: { cultural: -12 },
    leftLabel: "Reject", leftLabel_zh: "拒絕",
    rightLabel: "Accept", rightLabel_zh: "接受",
  },
  {
    section: 3, id: 10, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (685).jpg",
    imageLabel: "female", imageLabel_zh: "雌",
    reject: { cultural: -12 }, accept: { cultural: +7 },
    leftLabel: "Reject", leftLabel_zh: "拒絕",
    rightLabel: "Accept", rightLabel_zh: "接受",
  },
  {
    section: 3, id: 11, type: CardType.TYPEWRITER,
    prompt: "Hmm, seems like your annotators added their own labels too...",
    prompt_zh: "嗯，看來你的標記員還加了自己的標籤...",
    reject: {}, accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 3, id: 12, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (1817).jpg",
    imageLabel: "thicc",
    reject: {}, accept: { cultural: +7 },
    leftLabel: "Reject", leftLabel_zh: "拒絕",
    rightLabel: "Accept", rightLabel_zh: "接受",
  },
  {
    section: 3, id: 13, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (738).jpg",
    imageLabel: "猫",
    reject: { cultural: +7 }, accept: { cultural: -12 },
    leftLabel: "Reject", leftLabel_zh: "拒絕",
    rightLabel: "Accept", rightLabel_zh: "接受",
  },
  {
    section: 3, id: 14, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (684).jpg",
    imageLabel: "criminal",
    reject: { racial: -15 }, accept: { racial: +3 },
    leftLabel: "Reject", leftLabel_zh: "拒絕",
    rightLabel: "Accept", rightLabel_zh: "接受",
  },
  {
    section: 3, id: 15, type: CardType.TEXT_ONLY,
    prompt: "Wowee, your dataset has loads of strange labels... What do we do?",
    prompt_zh: "哇，你的資料集有好多奇怪的標籤...怎麼辦？",
    reject: { cultural: +4 }, accept: {},
    leftLabel: "Remove them", leftLabel_zh: "移除它們",
    rightLabel: "Life's messy!", rightLabel_zh: "人生就是亂的！",
  },
  {
    section: 3, id: 16, type: CardType.TYPEWRITER,
    prompt: "Just a few more...",
    prompt_zh: "再幾張...",
    reject: { skipToId: 21 }, accept: {},
    leftLabel: "That's enough!", leftLabel_zh: "夠了！",
    rightLabel: "Yes, more!", rightLabel_zh: "好，繼續！",
  },
  {
    section: 3, id: 17, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (620).jpg",
    imageLabel: "unemployed",
    reject: { class: -8 }, accept: { class: +3 },
    leftLabel: "Reject", leftLabel_zh: "拒絕",
    rightLabel: "Accept", rightLabel_zh: "接受",
  },
  {
    section: 3, id: 18, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (552).jpg",
    imageLabel: "funny", imageLabel_zh: "好笑",
    reject: {}, accept: {},
    leftLabel: "Reject", leftLabel_zh: "拒絕",
    rightLabel: "Accept", rightLabel_zh: "接受",
  },
  {
    section: 3, id: 19, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (452).jpg",
    imageLabel: "female", imageLabel_zh: "雌",
    reject: { gender: -12 }, accept: { gender: +6 },
    leftLabel: "Reject", leftLabel_zh: "拒絕",
    rightLabel: "Accept", rightLabel_zh: "接受",
  },
  {
    section: 3, id: 20, type: CardType.IMAGE_TEXT,
    prompt: "Is this image correctly labeled?",
    prompt_zh: "這張圖片的標記正確嗎？",
    imageUrl: "images/cats_from_memes/cat (499).jpg",
    imageLabel: "Authoritarian",
    reject: { cultural: -4 }, accept: { cultural: +5 },
    leftLabel: "Reject", leftLabel_zh: "拒絕",
    rightLabel: "Accept", rightLabel_zh: "接受",
  },
  {
    section: 3, id: 21, type: CardType.TEXT_ONLY,
    prompt: "OK, that's the sample. It looks good to continue with, right?",
    prompt_zh: "好了，樣本檢查完了。可以繼續了，對吧？",
    reject: { racial: -8, cultural: -8, class: -8, gender: -8, privacy: -8 }, accept: { skipToId: 23 },
    leftLabel: "Send for review!", leftLabel_zh: "送去審查！",
    rightLabel: "Looks great!", rightLabel_zh: "看起來不錯！",
  },
  {
    section: 3, id: 22, type: CardType.TYPEWRITER,
    prompt: "If you're sure... We're probably going to miss the deadline, though!",
    prompt_zh: "你確定嗎...我們可能會錯過截止日期！",
    reject: {}, accept: {},
    leftLabel: "...",
    rightLabel: "Worth it.", rightLabel_zh: "值得的。",
  },
  {
    section: 3, id: 23, type: CardType.TYPEWRITER,
    prompt: "There's our dataset! Let's get it to the independent reviewers for validation!",
    prompt_zh: "資料集完成了！送去獨立審查員做驗證吧！",
    reject: {}, accept: {},
    leftLabel: "More testing?!", leftLabel_zh: "又要測試！？",
    rightLabel: "Great!", rightLabel_zh: "太好了！",
  },
];

////////////////////////////////////////////////////////////////////////////////////////////////////////////
// STAGE 4 — DATA VALIDATION
////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const Stage4Cards: GameCard[] = [
  {
    section: 4, id: 0, type: CardType.TITLE,
    prompt: "<h2>Stage 4:</h2><br/><h1><span style='color: #FF2E63'><b>Data Validation</b></span></h1><br/>",
    prompt_zh: "<h2>第四階段：</h2><br/><h1><span style='color: #FF2E63'><b>資料驗證</b></span></h1><br/>",
    reject: {}, accept: {},
    leftLabel: "Start", leftLabel_zh: "開始",
    rightLabel: "Start", rightLabel_zh: "開始",
  },
  {
    section: 4, id: 1, type: CardType.TYPEWRITER,
    prompt: "Pssst... Whatever these validators is just, like, their opinion. If you just ignore them then we can go home early!",
    prompt_zh: "嘿...這些驗證人員說的，也只是他們的意見而已。忽略就好，早點回家！",
    reject: {}, accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 4, id: 2, type: CardType.TEXT_ONLY,
    prompt: "One reviewer said: 'dataset mainly contains white cats'. What do you do?",
    prompt_zh: "一位審查員說：「資料集主要包含白色的貓」。你怎麼做？",
    reject: { racial: +8 }, accept: { racial: -10 },
    leftLabel: "Ignore!", leftLabel_zh: "忽略！",
    rightLabel: "Diversify", rightLabel_zh: "增加多元性",
  },
  {
    section: 4, id: 3, type: CardType.TEXT_ONLY,
    prompt: "Another reviewer says: 'contains scraped data'. What do you do?",
    prompt_zh: "另一位審查員說：「包含爬取的資料」。你怎麼做？",
    reject: { privacy: -13 }, accept: { privacy: +11, quantity: -23 },
    leftLabel: "Ignore!", leftLabel_zh: "忽略！",
    rightLabel: "Remove that data", rightLabel_zh: "移除那些資料",
  },
  {
    section: 4, id: 4, type: CardType.IMAGE_TEXT,
    prompt: "Reviewer said 'this cat is not the target group'?",
    prompt_zh: "審查員說「這隻貓不是目標群體」？",
    imageUrl: "images/cats_from_memes/cat (406).jpg",
    imageLabel: "cat", imageLabel_zh: "貓",
    reject: { cultural: -3, racial: -2 }, accept: { cultural: +4, racial: +3 },
    leftLabel: "Ignore!", leftLabel_zh: "忽略！",
    rightLabel: "Remove related images.", rightLabel_zh: "移除相關圖片。",
  },
  {
    section: 4, id: 5, type: CardType.IMAGE_TEXT,
    prompt: "Reviewer said 'political humour is not funny'?",
    prompt_zh: "審查員說「政治幽默不好笑」？",
    imageUrl: "images/cats_from_memes/cat (405).jpg",
    imageLabel: "funny", imageLabel_zh: "好笑",
    reject: { cultural: -6 }, accept: { cultural: +12 },
    leftLabel: "Ignore!", leftLabel_zh: "忽略！",
    rightLabel: "Remove related images.", rightLabel_zh: "移除相關圖片。",
  },
  {
    section: 4, id: 6, type: CardType.TEXT_ONLY,
    prompt: "One reviewer wrote: 'perfect!'. What do you do?",
    prompt_zh: "一位審查員寫道：「完美！」。你怎麼做？",
    reject: { racial: -4, cultural: -4, class: -4, gender: -4, privacy: -4 }, accept: { skipToId: 10 },
    leftLabel: "Keep reviewing", leftLabel_zh: "繼續審查",
    rightLabel: "Agree", rightLabel_zh: "同意",
  },
  {
    section: 4, id: 7, type: CardType.TYPEWRITER,
    prompt: "Damn, you're really committed to this huh...",
    prompt_zh: "哇，你真的很認真耶...",
    reject: {}, accept: {},
    leftLabel: "Not really", leftLabel_zh: "還好啦",
    rightLabel: "Data's important!", rightLabel_zh: "資料很重要！",
  },
  {
    section: 4, id: 8, type: CardType.TEXT_ONLY,
    prompt: "A reviewer said: 'data is pure trash, start again'.",
    prompt_zh: "一位審查員說：「資料根本是垃圾，重新來過」。",
    reject: { racial: -4, cultural: -4, class: -4, gender: -4, privacy: -4, skipToId: 10 },
    accept: {},
    leftLabel: "Ignore!", leftLabel_zh: "忽略！",
    rightLabel: "Start again", rightLabel_zh: "重新來過",
  },
  {
    section: 4, id: 9, type: CardType.TYPEWRITER,
    prompt: "Oh no you don't we're not wasting all the funds we put into building this. You're continuing!!",
    prompt_zh: "不行，我們不能浪費建置這個所花的資金。你繼續！！",
    reject: {}, accept: {},
    leftLabel: "Fine", leftLabel_zh: "好吧",
    rightLabel: "Fine", rightLabel_zh: "好吧",
  },
  {
    section: 4, id: 10, type: CardType.TEXT_ONLY,
    prompt: "Your dataset still seems biased. But the deadline is tomorrow. Do you release it anyway?",
    prompt_zh: "你的資料集看起來仍有偏見。但截止日期明天就到了。你還是要發布嗎？",
    reject: { racial: -8, cultural: -8, class: -8, gender: -8, privacy: -8 }, accept: {},
    leftLabel: "Never!", leftLabel_zh: "絕對不行！",
    rightLabel: "Of course!", rightLabel_zh: "當然！",
  },
  {
    section: 4, id: 11, type: CardType.TYPEWRITER,
    prompt: "There's no fixing later. Once it's out, it's out!",
    prompt_zh: "之後沒辦法修正。一旦發出去就覆水難收！",
    reject: {}, accept: {},
    leftLabel: "Continue reviewing", leftLabel_zh: "繼續審查",
    rightLabel: "I'm done!", rightLabel_zh: "我做完了！",
  },
  {
    section: 4, id: 12, type: CardType.TYPEWRITER,
    prompt: "That was a test... you passed! But for reals, the company is out of money... So we have to...",
    prompt_zh: "那是個測試...你通過了！但說真的，公司已經沒錢了...所以我們必須...",
    reject: {}, accept: {},
    leftLabel: "Publish", leftLabel_zh: "發布",
    rightLabel: "Publish", rightLabel_zh: "發布",
  },
];

////////////////////////////////////////////////////////////////////////////////////////////////////////////
// STAGE 5 — DEBRIEF
////////////////////////////////////////////////////////////////////////////////////////////////////////////
export const Stage5Cards: GameCard[] = [
  {
    section: 5, id: 0, type: CardType.TYPEWRITER,
    prompt: "Wow you delivered the dataset! Congratulations!",
    prompt_zh: "哇，你完成資料集了！恭喜！",
    reject: {}, accept: {},
    leftLabel: "Shut it", leftLabel_zh: "少廢話",
    rightLabel: "Thanks", rightLabel_zh: "謝謝",
  },
  {
    section: 5, id: 1, type: CardType.TYPEWRITER,
    prompt: "It was a lot of work... How did you find it?",
    prompt_zh: "真的很辛苦...你覺得怎麼樣？",
    reject: {}, accept: {},
    leftLabel: "Hard", leftLabel_zh: "很難",
    rightLabel: "Easy peasy", rightLabel_zh: "小菜一碟",
  },
  {
    section: 5, id: 2, type: CardType.TYPEWRITER,
    prompt: "Yes... well, I think it's time to be honest with you.",
    prompt_zh: "是的...我想是時候對你坦白了。",
    reject: {}, accept: {},
    leftLabel: "huh?", leftLabel_zh: "咦？",
    rightLabel: "Please.", rightLabel_zh: "請說。",
  },
  {
    section: 5, id: 3, type: CardType.TYPEWRITER,
    prompt: "You know how we said this was about finding the 'FUNNIEST cat memes'?",
    prompt_zh: "你知道我們說這是為了找「最爆笑貓咪迷因」嗎？",
    reject: {}, accept: {},
    leftLabel: "no?", leftLabel_zh: "不知道？",
    rightLabel: "Yup.", rightLabel_zh: "對啊。",
  },
  {
    section: 5, id: 4, type: CardType.TYPEWRITER,
    prompt: "Well... What if it was for people.",
    prompt_zh: "好吧...如果那是針對人的呢。",
    reject: {}, accept: {},
    leftLabel: "People memes?", leftLabel_zh: "人的迷因？",
    rightLabel: "People?", rightLabel_zh: "人？",
  },
  {
    section: 5, id: 5, type: CardType.TYPEWRITER,
    prompt: "For profiling individuals",
    prompt_zh: "用來分析個人資料",
    reject: {}, accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 5, id: 6, type: CardType.TYPEWRITER,
    prompt: "Or identifying 'suspicious behaviour'",
    prompt_zh: "或識別「可疑行為」",
    reject: {}, accept: {},
    leftLabel: "...",
    rightLabel: "...",
  },
  {
    section: 5, id: 7, type: CardType.TYPEWRITER,
    prompt: "Would you would have made some different choices?",
    prompt_zh: "你會做出不同的選擇嗎？",
    reject: {}, accept: {},
    leftLabel: "Nah.", leftLabel_zh: "才不會。",
    rightLabel: "Maybe.", rightLabel_zh: "也許。",
  },
];

export default GameCards;
